# Generated by Django 2.0.13 on 2020-07-06 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantite_commande', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Donateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=10)),
                ('nationalite', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hopitaux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('adress', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.CharField(max_length=40)),
                ('stock_groupe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Sang')),
            ],
        ),
        migrations.AddField(
            model_name='donateur',
            name='groupe_sanguin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Sang'),
        ),
        migrations.AddField(
            model_name='commande',
            name='groupe_sanguin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Sang'),
        ),
        migrations.AddField(
            model_name='commande',
            name='partenaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Hopitaux'),
        ),
    ]
